### PR TITLE
Development

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1)

### CODE REVIEW

**Comment by aledj2** [comment]
+@aledj2 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-:-LE9M8GB7H-dIaOym89H:bweg3f8)*

**Comment by aledj2** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[100k_geneworks_participants.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9QxjE143gmC6KqxNS:-LE9QxjF1GIxMarFrSsb:b-5un03s) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L13)):*
> ```Python
> 
> Takes an input csv file containing request ids and family ids in format sent
> in GeL results emailOutputs a csv file with patient information from Geneworks
> ```

minor - missing full stop.

---

*[100k_geneworks_participants.py, line 27 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9R-xfDoNxHW8YXW-e:-LE9R-xfDoNxHW8YXW-f:bhb1fy4) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L27)):*
> ```Python
> import pyodbc
> import pandas
> from pyCIPAPI.interpretation_requests import get_interpretation_request_list
> ```

Is this Jelly Py? maybe should clone and use the proper jelly py repo?

---

*[100k_geneworks_participants.py, line 66 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9OqBJBO8BUPtGRaGe:-LE9OqBJBO8BUPtGRaGf:b-v6dgwy) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L66)):*
> ```Python
>     Takes a dataframe containing ir_id and adds participant ID from CIPAPI
>     """
>     request_id_df['Participant Id'] = request_id_df['ir_id'].apply(get_participant_id)
> ```

Sorry could you add some comments explaining what .apply() does and that this is calling another function. Also that it does it for all rows?

---

*[100k_geneworks_participants.py, line 98 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9RU43CSEWjrwDyDjj:-LE9RU43CSEWjrwDyDjk:bxmat6l) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L98)):*
> ```Python
>     # Use CIPAPI to find participant IDs and add to dataframe
>     add_participant_id_to_df(ir_id_dataframe)
>     # Query Geneworks using list of participant IDs from dataframe, returens a dataframe with results
> ```

typo (sorry)

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1)*

**Comment by andyb3** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[100k_geneworks_participants.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9QxjE143gmC6KqxNS:-LEFB40bBJAPz6kHw4_C:bb7f2mf) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

minor - missing full stop.
</blockquote></details>

done

---

*[100k_geneworks_participants.py, line 27 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9R-xfDoNxHW8YXW-e:-LEFbiRQ7PhQZYkyPqFh:b-896fix) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L27)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Is this Jelly Py? maybe should clone and use the proper jelly py repo?
</blockquote></details>

Done.

---

*[100k_geneworks_participants.py, line 66 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9OqBJBO8BUPtGRaGe:-LEFcKIL13tbtysHeu_D:b-896fix) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L66)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Sorry could you add some comments explaining what .apply() does and that this is calling another function. Also that it does it for all rows?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1)*

**Comment by andyb3** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[100k_geneworks_participants.py, line 98 at r1](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-LE9RU43CSEWjrwDyDjj:-LEJDESj4EK0_x3Kvhsd:b-896fix) ([raw file](https://github.com/moka-guys/100k_patients_geneworks/blob/7f0710ffb7b8f4e60b8be2b39a31b75768f9c894/100k_geneworks_participants.py#L98)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

typo (sorry)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/100k_patients_geneworks/1#-:-LEOUrlGCe1r25ZYsyKY:bnfp4nl)*

**Pull request merged**
